// <auto-generated />
using System;
using CoreApi.Data.Archive;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreApi.Data.Migrations.Archive
{
    [DbContext(typeof(ArchiveDbContext))]
    [Migration("20260612221348_ArchiveInitialSchema")]
    partial class ArchiveInitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveBan", b =>
                {
                    b.Property<string>("BanKey")
                        .HasColumnType("text")
                        .HasColumnName("ban_key");

                    b.Property<long>("BannedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("banned_at");

                    b.Property<string>("BannedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("banned_by");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_identity");

                    b.HasKey("BanKey");

                    b.HasIndex("ServerId");

                    b.ToTable("archive_ban");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveBlock", b =>
                {
                    b.Property<string>("BlockKey")
                        .HasColumnType("text")
                        .HasColumnName("block_key");

                    b.Property<string>("Blocked")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blocked");

                    b.Property<string>("Blocker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blocker");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.HasKey("BlockKey");

                    b.ToTable("archive_block");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveChannel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<bool>("ModeratorOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("moderator_only");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("Position")
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    b.Property<string>("Section")
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("archive_channel");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveDirectMessage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ConversationKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("conversation_key")
                        .HasComputedColumnSql("LEAST(sender_identity, recipient_identity) || ':' || GREATEST(sender_identity, recipient_identity)", true);

                    b.Property<bool>("DeletedByRecipient")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted_by_recipient");

                    b.Property<bool>("DeletedBySender")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted_by_sender");

                    b.Property<long?>("EditedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("edited_at");

                    b.Property<string>("RecipientIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_identity");

                    b.Property<string>("SenderIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_identity");

                    b.Property<long>("SentAt")
                        .HasColumnType("bigint")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.HasIndex("ConversationKey", "SentAt");

                    b.ToTable("archive_direct_message");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveDmServerInvite", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invite_token");

                    b.Property<string>("RecipientIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_identity");

                    b.Property<string>("SenderIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_identity");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("archive_dm_server_invite");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveFriend", b =>
                {
                    b.Property<string>("PairKey")
                        .HasColumnType("text")
                        .HasColumnName("pair_key");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_a");

                    b.Property<string>("UserB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_b");

                    b.HasKey("PairKey");

                    b.ToTable("archive_friend");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveInvite", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.PrimitiveCollection<string[]>("AllowedUsernames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_usernames");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at");

                    b.Property<long?>("MaxUses")
                        .HasColumnType("bigint")
                        .HasColumnName("max_uses");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<long>("UseCount")
                        .HasColumnType("bigint")
                        .HasColumnName("use_count");

                    b.HasKey("Token");

                    b.HasIndex("ServerId");

                    b.ToTable("archive_invite");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveJoinRequest", b =>
                {
                    b.Property<string>("RequestKey")
                        .HasColumnType("text")
                        .HasColumnName("request_key");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<bool>("Declined")
                        .HasColumnType("boolean")
                        .HasColumnName("declined");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_identity");

                    b.HasKey("RequestKey");

                    b.HasIndex("ServerId");

                    b.ToTable("archive_join_request");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveMessage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<long?>("EditedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("edited_at");

                    b.Property<string>("SenderIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_identity");

                    b.Property<long>("SentAt")
                        .HasColumnType("bigint")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "SentAt");

                    b.ToTable("archive_message");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveReadState", b =>
                {
                    b.Property<string>("ReadKey")
                        .HasColumnType("text")
                        .HasColumnName("read_key");

                    b.Property<long>("LastReadAt")
                        .HasColumnType("bigint")
                        .HasColumnName("last_read_at");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope_key");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_identity");

                    b.HasKey("ReadKey");

                    b.ToTable("archive_read_state");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveServer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<string>("InvitePolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invite_policy");

                    b.Property<bool>("IsDiscoverable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_discoverable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_identity");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.ToTable("archive_server");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveServerMember", b =>
                {
                    b.Property<string>("MemberKey")
                        .HasColumnType("text")
                        .HasColumnName("member_key");

                    b.Property<long>("JoinedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<long?>("TimeoutUntil")
                        .HasColumnType("bigint")
                        .HasColumnName("timeout_until");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_identity");

                    b.HasKey("MemberKey");

                    b.HasIndex("ServerId");

                    b.ToTable("archive_server_member");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ArchiveUser", b =>
                {
                    b.Property<string>("Identity")
                        .HasColumnType("text")
                        .HasColumnName("identity");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Identity");

                    b.ToTable("archive_user");
                });

            modelBuilder.Entity("CoreApi.Data.Archive.ReplicationState", b =>
                {
                    b.Property<string>("TableName")
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.Property<DateTimeOffset?>("LastFullSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_full_sync_at");

                    b.Property<DateTimeOffset?>("LastReconcileAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reconcile_at");

                    b.Property<long>("RowCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("row_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TableName");

                    b.ToTable("replication_state");
                });
#pragma warning restore 612, 618
        }
    }
}
